version: "3"


services:

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - 'cluster.name=elasticsearch'  # 设置集群名称为elasticsearch
      - 'discovery.type=single-node'  # 以单一节点模式启动
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'  # 设置使用jvm内存大小
    volumes:
      - /etc/localtime:/etc/localtime
      - ./es/plugins:/usr/share/elasticsearch/plugins  # 插件文件挂载
      - ./es/data:/usr/share/elasticsearch/data  # 数据文件挂载
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging-net

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: -Xms1024m -Xmx1024m
      TZ: Asia/Shanghai
      MONITORING_ENABLED: false
    volumes:
      - /etc/localtime:/etc/localtime
      - './logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml'
      - './logstash/logstash-audit.conf:/usr/share/logstash/pipeline/logstash-audit.conf'
      - './logstash/logstash-user-action.conf:/usr/share/logstash/pipeline/logstash-user-action.conf'
    ports:
      - '5044:5044'
      - '50000:50000/tcp'
      - '50000:50000/udp'
      - '9600:9600'
    links:
      - elasticsearch:es  # 可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch
    networks:
      - logging-net

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  # 设置访问elasticsearch的地址
      - 'elasticsearch.hosts=http://es:9200'  # 设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN
    volumes:
      - /etc/localtime:/etc/localtime
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch
    networks:
      - logging-net


networks:

  monitor-net:
    driver: bridge
    name: logging-net
    ipam:
      driver: default
      config:
        - subnet: 172.30.3.0/24
